import { $randomInt } from './$randomInt';

describe('$randomInt()', () => {
  let randomSpy: jest.SpyInstance<number, []>;

  beforeEach(() => {
    randomSpy = jest.spyOn(Math, 'random').mockName('Math.random').mockReturnValue(0.5);
  });

  afterEach(() => {
    randomSpy.mockRestore();
  });

  it('should return a number generated by `Math.random()`', () => {
    const minimum = 0;
    const maximum = 5;
    const operator = {
      $randomInt: [minimum, maximum] as [number, number]
    };
    const value = undefined;
    const num = $randomInt({ value, operator });

    expect(randomSpy).toBeCalledTimes(1);
    expect(typeof num).toBe('number');
  });
});
